### ISSUE TITLE
intro do DOM codealong is incongruous

### ISSUE THREAD

**Issue by AlexFriedland** [learn-co-curriculum/js-dom-and-events-intro-to-the-dom-code-along#1]
hey guys, i was told to reach out by TC on learn.co

this lesson doesn't really make sense in the context of the lesson structure, let alone the title. It says it's the DOM codealong and to insert the example code in the index.js, but there is no lab / file to open, and you can't insert the commands into the DOM... it also goes over HTML concepts covered way back. 

take a look, it doesn't really make sense (doesn't tell you how specifically to code along, also says it's a DOM codealong and then moves away from DOM in the lesson without stating it)... and there's no way to code along with it.

alex

**Comment by jenmyers** [comment]
This material has been updated.
