### ISSUE TITLE
Intro to Dom Codealong - tests will not pass even when copying/pasting index.html from solution branch

### ISSUE THREAD

**Issue by mmelmer** [learn-co-curriculum/js-dom-and-events-intro-to-the-dom-code-along#9]

**Comment by sgharms** [comment]
It looks to me from : https://github.com/mmelmer/js-dom-and-events-intro-to-the-dom-code-along-v-000/commit/1ccec7a8225c40ba75e217ef4fcfe389d5fdbf76

That you were putting your HTML code outside the body. But it seems that you got this working.

Is this still broken? Please verify.
